# Generated by Django 4.1.5 on 2023-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("url", models.URLField()),
                ("embed_url", models.URLField()),
                ("broadcaster_id", models.TextField()),
                ("broadcaster_name", models.TextField()),
                ("creator_id", models.TextField()),
                ("creator_name", models.TextField()),
                ("video_id", models.TextField()),
                ("game_id", models.TextField()),
                ("title", models.TextField()),
                ("view_count", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("thumbnail_url", models.TextField()),
                ("duration", models.FloatField()),
                ("vod_offset", models.IntegerField()),
            ],
        ),
    ]
