# Generated by Django 4.1.5 on 2023-01-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(null=True)),
                ("embed_url", models.URLField(null=True)),
                ("broadcaster_id", models.CharField(max_length=100, null=True)),
                ("broadcaster_name", models.CharField(max_length=100, null=True)),
                ("creator_id", models.CharField(max_length=100, null=True)),
                ("creator_name", models.CharField(max_length=100, null=True)),
                ("video_id", models.CharField(max_length=100, null=True)),
                ("game_id", models.CharField(max_length=100, null=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("view_count", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("thumbnail_url", models.URLField(null=True)),
                ("duration", models.FloatField(null=True)),
                ("vod_offset", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
        ),
    ]
