# Generated by Django 4.1.5 on 2023-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="broadcaster_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="broadcaster_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="creator_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="creator_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="duration",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="embed_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="game_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="thumbnail_url",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="video_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="view_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="vod_offset",
            field=models.IntegerField(null=True),
        ),
    ]
