# Generated by Django 4.1.5 on 2023-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_alter_clip_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
