# Generated by Django 4.1.5 on 2023-01-22 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manager", "0005_myuser_alter_clip_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="date_added",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="MyUser",
        ),
    ]
