# Generated by Django 4.1.5 on 2023-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_clip_date_added_alter_clip_account_delete_myuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
            ],
        ),
    ]
