# Generated by Django 4.1.5 on 2023-01-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_resettime"),
    ]

    operations = [
        migrations.AddField(
            model_name="resettime",
            name="clip_amount",
            field=models.IntegerField(default=2),
        ),
    ]
