# Generated by Django 4.1.5 on 2023-01-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_rename_clip_amount_resettime_max_clips"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResetTime",
            new_name="ResetData",
        ),
    ]
