# Generated by Django 4.1.5 on 2023-01-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0010_rename_resettime_resetdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="rank",
            field=models.IntegerField(null=True),
        ),
    ]
