# Generated by Django 4.1.5 on 2023-01-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_clip_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetdata",
            name="ranks",
            field=models.IntegerField(default=5),
        ),
    ]
