# Generated by Django 4.1.5 on 2023-01-23 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0014_allowedchannel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resetdata",
            name="clip_limit_to_channels",
        ),
        migrations.AddField(
            model_name="resetdata",
            name="end_date_time",
            field=models.DateTimeField(default=datetime.datetime(2038, 1, 19, 3, 14)),
        ),
    ]
